[package]
name = "rust_hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
num = "0.4"

[profile.release]
paic = "abort"

[[bin]]
name = "todo"
path = "src/todo/main.rs"
